### ISSUE TITLE
source code compilation error

### ISSUE THREAD

**Issue by engrmasood2002** [Subangkar/Distance-Vector-Routing-Protocol-CPP-Implementation#1]
I get errors compiling as indicated in readme file.
c++ router.cpp -std=c++17 -o router.out  
I have ubuntu 16.04 installed with latest g++ and C++ installed. Error shows missing ';' in every line with auto keyword.

**Comment by Subangkar** [comment]
I have just compiled this again on Ubuntu 18.04.1
This is absolutely working with C++17. 
I have following g++ version

> c++ --version

shows

`g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

You may give a try with `g++` in place of `c++`

**Comment by engrmasood2002** [comment]
Hi, this is output of command to get c++ version
> c++ --version
> c++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
and for g++ --version 
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
I think i need to upgrade g++ or c++ to 7.4.0 or upgrade to Ubuntu 18.04
otherwise i would continue to get error as i have already tried compilation with c++ and g++

**Comment by Subangkar** [comment]
Likely, g++ or c++ version is the issue here.
Ubuntu version should not be a problem at least for cpp source compilation.

**Comment by engrmasood2002** [comment]
Hi Subangkar 
Your help is really appreciated, Can you help me on implementing OLSR protocol, i have found from OLSR.org that source code is lengthy. I want to have implementation of OLSR like your DVRP implementation, simple and understandable.
